---

- hosts: all
  become: true
  tasks:

  - name: Installs apache2, php support package, and updates repo for Ubuntu
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

