- name: Install apache and php for CentOS servers
  tags: apache,httpd,centos
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: Start Apache2 service on Ubuntu servers
  tags: apache2,ubuntu
  service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"

- name: Install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: copy default html file to website
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
